/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

import BasicClass.Customer;
import BasicClass.IndemnifyRoom;
import Model.IndemnifyModel;
import java.sql.Timestamp;
import java.text.DecimalFormat;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JTextField;
import javax.swing.event.TableModelEvent;
import javax.swing.event.TableModelListener;
import javax.swing.table.DefaultTableCellRenderer;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Admin
 */
public class IndemnifyForm extends javax.swing.JPanel {

    private IndemnifyModel indemnifyModel = new IndemnifyModel();
    private long tienboithuong = 0;

    /**
     * Creates new form IndemnifyForm
     */
    public IndemnifyForm() {
        initComponents();
        showIndemnify();
        showMathuephong();
        chitietboithuong.getModel().addTableModelListener(new TableModelListener() {
            @Override
            public void tableChanged(TableModelEvent e) {
                tienboithuong = 0;
                for (int i = 0; i < chitietboithuong.getRowCount(); i++) {
                    tienboithuong += (long) chitietboithuong.getValueAt(i, 1);
                }
                jtextTienboithuong.setText(new DecimalFormat("#,###.0 vnd").format(tienboithuong));
            }
        });

    }

    // Lấy dữ liệu trong sql quy định bồi thuòng ra bảng
    public void showIndemnify() {
        DefaultTableCellRenderer renderer = new DefaultTableCellRenderer();
        renderer.setHorizontalAlignment(JLabel.CENTER);
        for (int i = 0; i < qdboithuongTable.getColumnCount(); i++) {
            qdboithuongTable.getColumnModel().getColumn(i).setHeaderRenderer(renderer);
            qdboithuongTable.getColumnModel().getColumn(i).setCellRenderer(renderer);
        }
        indemnifyModel.getIndemnify((DefaultTableModel) qdboithuongTable.getModel());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        loai_buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel9 = new javax.swing.JPanel();
        jPanelTren = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jPanel10 = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        jPanel11 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jPanelDuoi = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        thuRadiobtn = new javax.swing.JRadioButton();
        chiRadiobtn = new javax.swing.JRadioButton();
        JTngaylap = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jTextHotenkh = new javax.swing.JTextField();
        mathuephongComboBox = new javax.swing.JComboBox<>();
        jPanel6 = new javax.swing.JPanel();
        xoabtn = new javax.swing.JButton();
        lammoibtn = new javax.swing.JButton();
        phieubthuongbtn = new javax.swing.JButton();
        jPanel7 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        chitietboithuong = new javax.swing.JTable();
        jPanel8 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jtextTienboithuong = new javax.swing.JTextField();
        jPanel4 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        qdboithuongTable = new javax.swing.JTable();

        javax.swing.GroupLayout jPanel9Layout = new javax.swing.GroupLayout(jPanel9);
        jPanel9.setLayout(jPanel9Layout);
        jPanel9Layout.setHorizontalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 837, Short.MAX_VALUE)
        );
        jPanel9Layout.setVerticalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 514, Short.MAX_VALUE)
        );

        setBackground(new java.awt.Color(204, 204, 255));
        setPreferredSize(new java.awt.Dimension(1006, 600));
        setRequestFocusEnabled(false);
        setLayout(new java.awt.BorderLayout());

        jPanelTren.setLayout(new java.awt.BorderLayout());

        jPanel1.setBackground(getBackground());
        jPanel1.setPreferredSize(new java.awt.Dimension(1010, 22));
        jPanel1.setLayout(new java.awt.GridLayout(1, 0));

        jLabel1.setFont(new java.awt.Font("Times New Roman", 3, 14)); // NOI18N
        jLabel1.setText("Quy định bồi thường:");
        jLabel1.setPreferredSize(new java.awt.Dimension(110, 17));
        jPanel1.add(jLabel1);

        jLabel2.setFont(new java.awt.Font("Times New Roman", 3, 14)); // NOI18N
        jLabel2.setText("Chi tiết bồi thường:");
        jPanel1.add(jLabel2);

        jPanelTren.add(jPanel1, java.awt.BorderLayout.PAGE_END);

        jPanel2.setBackground(getBackground());
        jPanel2.setPreferredSize(new java.awt.Dimension(1010, 80));
        jPanel2.setLayout(new java.awt.BorderLayout());

        jPanel10.setPreferredSize(new java.awt.Dimension(750, 80));
        jPanel10.setLayout(new java.awt.BorderLayout());

        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/rsz_khach-san-6-sao-10xoay.jpg"))); // NOI18N
        jPanel10.add(jLabel10, java.awt.BorderLayout.CENTER);

        jPanel2.add(jPanel10, java.awt.BorderLayout.LINE_END);

        jPanel11.setLayout(new java.awt.BorderLayout());

        jLabel4.setBackground(getBackground());
        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/rsz_khach-san-6-sao-10.jpg"))); // NOI18N
        jPanel11.add(jLabel4, java.awt.BorderLayout.CENTER);

        jPanel2.add(jPanel11, java.awt.BorderLayout.CENTER);

        jPanelTren.add(jPanel2, java.awt.BorderLayout.CENTER);

        add(jPanelTren, java.awt.BorderLayout.PAGE_START);

        jPanelDuoi.setBackground(getBackground());
        jPanelDuoi.setLayout(new java.awt.BorderLayout(10, 0));

        jPanel3.setBackground(jPanel3.getBackground());
        jPanel3.setPreferredSize(new java.awt.Dimension(765, 535));
        jPanel3.setRequestFocusEnabled(false);
        jPanel3.setLayout(new java.awt.BorderLayout());

        jPanel5.setBackground(getBackground());
        jPanel5.setLayout(new java.awt.GridBagLayout());

        jLabel3.setText("Mã thuê Phòng:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.ipady = 6;
        gridBagConstraints.weightx = 0.1;
        gridBagConstraints.weighty = 0.1;
        jPanel5.add(jLabel3, gridBagConstraints);

        jLabel5.setText("Loại bồi thường:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.ipady = 2;
        gridBagConstraints.weightx = 0.1;
        gridBagConstraints.weighty = 0.1;
        jPanel5.add(jLabel5, gridBagConstraints);

        thuRadiobtn.setBackground(getBackground());
        loai_buttonGroup1.add(thuRadiobtn);
        thuRadiobtn.setSelected(true);
        thuRadiobtn.setText("Thu ");
        thuRadiobtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                thuRadiobtnActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.ipady = 2;
        gridBagConstraints.weightx = 0.1;
        gridBagConstraints.weighty = 0.1;
        jPanel5.add(thuRadiobtn, gridBagConstraints);

        chiRadiobtn.setBackground(getBackground());
        loai_buttonGroup1.add(chiRadiobtn);
        chiRadiobtn.setText("Chi");
        chiRadiobtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chiRadiobtnActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.ipady = 2;
        gridBagConstraints.weightx = 0.1;
        gridBagConstraints.weighty = 0.1;
        jPanel5.add(chiRadiobtn, gridBagConstraints);

        JTngaylap.setBackground(getBackground());
        JTngaylap.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        JTngaylap.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(0, 0, 0)));
        JTngaylap.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JTngaylapActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.ipady = 6;
        gridBagConstraints.weightx = 0.1;
        gridBagConstraints.weighty = 0.1;
        gridBagConstraints.insets = new java.awt.Insets(0, -150, 0, 170);
        jPanel5.add(JTngaylap, gridBagConstraints);

        jLabel7.setText("Ngày lập:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.ipady = 6;
        gridBagConstraints.weightx = 0.1;
        gridBagConstraints.weighty = 0.1;
        jPanel5.add(jLabel7, gridBagConstraints);

        jLabel8.setFont(new java.awt.Font("Times New Roman", 3, 12)); // NOI18N
        jLabel8.setText("Chi tiết nội dung:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 5;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        jPanel5.add(jLabel8, gridBagConstraints);

        jLabel9.setText("Họ tên khách hàng:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.ipady = 6;
        gridBagConstraints.weightx = 0.1;
        gridBagConstraints.weighty = 0.1;
        jPanel5.add(jLabel9, gridBagConstraints);

        jTextHotenkh.setBackground(getBackground());
        jTextHotenkh.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextHotenkh.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(0, 0, 0)));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.ipady = 6;
        gridBagConstraints.weightx = 0.1;
        gridBagConstraints.weighty = 0.1;
        gridBagConstraints.insets = new java.awt.Insets(0, -150, 0, 170);
        jPanel5.add(jTextHotenkh, gridBagConstraints);

        mathuephongComboBox.setName(""); // NOI18N
        mathuephongComboBox.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                mathuephongComboBoxFocusLost(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        jPanel5.add(mathuephongComboBox, gridBagConstraints);

        jPanel3.add(jPanel5, java.awt.BorderLayout.PAGE_START);

        jPanel6.setLayout(new java.awt.GridLayout(1, 0));

        xoabtn.setText("Xóa");
        xoabtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                xoabtnActionPerformed(evt);
            }
        });
        jPanel6.add(xoabtn);

        lammoibtn.setText("Làm mới ");
        lammoibtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lammoibtnActionPerformed(evt);
            }
        });
        jPanel6.add(lammoibtn);

        phieubthuongbtn.setText("In phiếu bồi thường");
        phieubthuongbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                phieubthuongbtnActionPerformed(evt);
            }
        });
        jPanel6.add(phieubthuongbtn);

        jPanel3.add(jPanel6, java.awt.BorderLayout.PAGE_END);

        jPanel7.setLayout(new java.awt.BorderLayout());

        chitietboithuong.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Chi tiết ", "Chi phí"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Object.class, java.lang.Long.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        chitietboithuong.setRowHeight(25);
        chitietboithuong.setRowMargin(2);
        chitietboithuong.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                chitietboithuongMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(chitietboithuong);

        jPanel7.add(jScrollPane2, java.awt.BorderLayout.CENTER);

        jPanel8.setBackground(getBackground());
        jPanel8.setPreferredSize(new java.awt.Dimension(500, 50));
        jPanel8.setLayout(new java.awt.GridBagLayout());

        jLabel6.setFont(new java.awt.Font("Tahoma", 3, 14)); // NOI18N
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setText("Tổng Chi phí:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.weightx = 0.1;
        gridBagConstraints.weighty = 0.1;
        jPanel8.add(jLabel6, gridBagConstraints);

        jtextTienboithuong.setBackground(new java.awt.Color(255, 255, 51));
        jtextTienboithuong.setFont(new java.awt.Font("Tahoma", 3, 14)); // NOI18N
        jtextTienboithuong.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jtextTienboithuong.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(0, 0, 0)));
        jtextTienboithuong.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtextTienboithuongActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.weightx = 0.1;
        gridBagConstraints.weighty = 0.1;
        jPanel8.add(jtextTienboithuong, gridBagConstraints);

        jPanel7.add(jPanel8, java.awt.BorderLayout.PAGE_END);

        jPanel3.add(jPanel7, java.awt.BorderLayout.CENTER);

        jPanelDuoi.add(jPanel3, java.awt.BorderLayout.LINE_END);

        jPanel4.setPreferredSize(new java.awt.Dimension(430, 402));
        jPanel4.setLayout(new java.awt.GridLayout(1, 0));

        qdboithuongTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Mã nội dung", "Nội dung", "Giá trị"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Object.class, java.lang.String.class, java.lang.Long.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        qdboithuongTable.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        qdboithuongTable.setShowGrid(true);
        qdboithuongTable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                qdboithuongTableMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(qdboithuongTable);

        jPanel4.add(jScrollPane1);

        jPanelDuoi.add(jPanel4, java.awt.BorderLayout.CENTER);

        add(jPanelDuoi, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents

    private void jtextTienboithuongActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtextTienboithuongActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtextTienboithuongActionPerformed

    //Lấy mã phòng trong combobox
    public void showMathuephong() {
        indemnifyModel.pickMathuephong(mathuephongComboBox);

    }

    //click các quy định đền bù
    DefaultTableModel chitietbtTableModel = new DefaultTableModel();

    private void qdboithuongTableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_qdboithuongTableMouseClicked
//        ArrayList<IndemnifyRoom> arrayList = new ArrayList<>();
        Timestamp ngaylap = new Timestamp(System.currentTimeMillis());
        JTngaylap.setText(String.valueOf(ngaylap));
        IndemnifyRoom indemnifyRoom = new IndemnifyRoom();
        indemnifyRoom.setNoidung(qdboithuongTable.getValueAt(qdboithuongTable.getSelectedRow(), 1).toString());
        indemnifyRoom.setChiphi((long) qdboithuongTable.getValueAt(qdboithuongTable.getSelectedRow(), 2));
        //arrayList.add(indemnifyRoom);
        Object[] row = new Object[2];
//        row[0] = arrayList.get(0).getNoidung();
//        row[1] = arrayList.get(0).getChiphi();
        row[0] = indemnifyRoom.getNoidung();
        row[1] = indemnifyRoom.getChiphi();
//        tienboithuong = tienboithuong + (long) arrayList.get(0).getChiphi();
        tienboithuong = tienboithuong + (long) indemnifyRoom.getChiphi();
        chitietbtTableModel = (DefaultTableModel) chitietboithuong.getModel();
        chitietbtTableModel.addRow(row);
        DefaultTableCellRenderer renderer = new DefaultTableCellRenderer();
        renderer.setHorizontalAlignment(JLabel.CENTER);
        for (int i = 0; i < chitietboithuong.getColumnCount(); i++) {
            chitietboithuong.getColumnModel().getColumn(i).setHeaderRenderer(renderer);
            chitietboithuong.getColumnModel().getColumn(i).setCellRenderer(renderer);
        }
        chitietboithuong.updateUI();
        //TextChitiet.setText(TextChitiet.getText().concat(qdboithuongTable.getValueAt(qdboithuongTable.getSelectedRow(), 1).toString()) + "\n");
        jtextTienboithuong.setText(new DecimalFormat("#,###.0 vnd").format(tienboithuong));
    }//GEN-LAST:event_qdboithuongTableMouseClicked

    private void JTngaylapActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JTngaylapActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_JTngaylapActionPerformed

    private void chitietboithuongMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_chitietboithuongMouseClicked
//         if (evt.getModifiers() == InputEvent.BUTTON3_MASK) {
//        chitietbtTableModel.removeRow(chitietboithuong.getSelectedRow());
//        }
    }//GEN-LAST:event_chitietboithuongMouseClicked

    //Xóa các nội dung vừa chọn trong bảng chi tiết bồi thường
    private void xoabtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_xoabtnActionPerformed
        if (chitietboithuong.getRowCount() > 0) {
            chitietbtTableModel.removeRow(chitietboithuong.getSelectedRow());
        } else {
            JOptionPane.showMessageDialog(null, "Không còn Chi tiết để xóa");
        }
    }//GEN-LAST:event_xoabtnActionPerformed

    //Làm mới lại thu chi bồi thường
    private void lammoibtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lammoibtnActionPerformed
        mathuephongComboBox.removeAllItems();
        showMathuephong();
        jTextHotenkh.setText("");
        JTngaylap.setText("");
        int n = chitietboithuong.getRowCount();
        for (int i = 0; i < n; i++) {
            chitietbtTableModel.removeRow(0);
        }
    }//GEN-LAST:event_lammoibtnActionPerformed

    // thêm phiếu vào database
    private void phieubthuongbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_phieubthuongbtnActionPerformed

        IndemnifyRoom indemnifyRoom = new IndemnifyRoom();
        if (loai_buttonGroup1.getSelection().equals(thuRadiobtn.getModel())) {
            indemnifyRoom.setLoai("Thu");
        } else {
            indemnifyRoom.setLoai("Chi");
        }
//        indemnifyRoom.setNgaylap(Timestamp.valueOf(JTngaylap.getText()));
        indemnifyRoom.setMathuephong(Integer.parseInt(mathuephongComboBox.getSelectedItem().toString()));
        tienboithuong = 0;
        JTextField swap = new JTextField();
        for (int i = 0; i < chitietboithuong.getRowCount(); i++) {
            tienboithuong += (long) chitietboithuong.getValueAt(i, 1);
            swap.setText(swap.getText().concat(chitietboithuong.getValueAt(i, 0).toString()) + "\n- ");
        }
        indemnifyRoom.setChiphi(tienboithuong);
        indemnifyRoom.setNoidung(swap.getText());
        indemnifyModel.addPhieuboithuong(indemnifyRoom);
        JOptionPane.showMessageDialog(null, "Đã thêm thành công!");
    }//GEN-LAST:event_phieubthuongbtnActionPerformed

// Click Vào "Chi" để làm mới lại bảng
    private void chiRadiobtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chiRadiobtnActionPerformed
        int n = chitietboithuong.getRowCount();
        for (int i = 0; i < n; i++) {
            chitietbtTableModel.removeRow(0);
        }
        IndemnifyRoom indemnifyRoom = new IndemnifyRoom();
        indemnifyRoom.setNoidung(" ");
        indemnifyRoom.setChiphi(0);
        Object[] row = new Object[2];
        row[0] = indemnifyRoom.getNoidung();
        row[1] = indemnifyRoom.getChiphi();
        chitietbtTableModel = (DefaultTableModel) chitietboithuong.getModel();
        chitietbtTableModel.addRow(row);
        DefaultTableCellRenderer renderer = new DefaultTableCellRenderer();
        renderer.setHorizontalAlignment(JLabel.CENTER);
        for (int i = 0; i < chitietboithuong.getColumnCount(); i++) {
            chitietboithuong.getColumnModel().getColumn(i).setHeaderRenderer(renderer);
            chitietboithuong.getColumnModel().getColumn(i).setCellRenderer(renderer);
        }
        chitietboithuong.updateUI();
        Timestamp timestamp = new Timestamp(System.currentTimeMillis());
        JTngaylap.setText(timestamp.toString());
    }//GEN-LAST:event_chiRadiobtnActionPerformed

    //Click vào "Thu" để làm mới lại bảng
    private void thuRadiobtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_thuRadiobtnActionPerformed
        int n = chitietboithuong.getRowCount();
        for (int i = 0; i < n; i++) {
            chitietbtTableModel.removeRow(0);
        }
    }//GEN-LAST:event_thuRadiobtnActionPerformed

    //Chọn mã thuê phòng để lấy ra tên khách hàng
    private void mathuephongComboBoxFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_mathuephongComboBoxFocusLost
        Customer customer = new IndemnifyModel().getNameCustomer(Integer.parseInt(mathuephongComboBox.getSelectedItem().toString()));
        if (customer != null) {
            jTextHotenkh.setText(customer.getHotenkh());
        } else {
            customer = null;
        }

    }//GEN-LAST:event_mathuephongComboBoxFocusLost

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField JTngaylap;
    private javax.swing.JRadioButton chiRadiobtn;
    private javax.swing.JTable chitietboithuong;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JPanel jPanelDuoi;
    private javax.swing.JPanel jPanelTren;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextField jTextHotenkh;
    private javax.swing.JTextField jtextTienboithuong;
    private javax.swing.JButton lammoibtn;
    private javax.swing.ButtonGroup loai_buttonGroup1;
    public javax.swing.JComboBox<String> mathuephongComboBox;
    private javax.swing.JButton phieubthuongbtn;
    private javax.swing.JTable qdboithuongTable;
    private javax.swing.JRadioButton thuRadiobtn;
    private javax.swing.JButton xoabtn;
    // End of variables declaration//GEN-END:variables
}
