/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

import BasicClass.Dichvu;
import BasicClass.Dichvuphong;
import Model.ServiceModel;
import java.util.ArrayList;
import java.sql.SQLException;
import java.sql.Timestamp;
import java.text.SimpleDateFormat;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.RowFilter;
import javax.swing.RowSorter;
import javax.swing.SortOrder;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;
import javax.swing.table.TableRowSorter;
//import org.jetbrains.annotations.Nullable;
import javax.swing.event.DocumentEvent;
import javax.swing.event.DocumentListener;

/**
 *
 * @author Admin
 */
public class ServiceForm extends javax.swing.JDialog {

    private int maphong$;
    private int mathuephong$;
    private ServiceModel serviceModel = new ServiceModel();

    public ServiceForm(java.awt.Frame parent, boolean modal, int maphong, int mathuephong) {
        super(parent, modal);
        initComponents();
        maphong$ = maphong;
        mathuephong$ = mathuephong;
        tablelichsusudung.setEnabled(false);
        AddServices();
        adddichvuphong();
        TableRowSorter<TableModel> rowSorter = new TableRowSorter<>(Servicestablemodel);
        serviceList.setRowSorter(rowSorter);
        txtSearch.getDocument().addDocumentListener(new DocumentListener() {
            @Override
            public void insertUpdate(DocumentEvent e) {
                String OwO = txtSearch.getText();
                if (OwO.trim().length() == 0) {
                    rowSorter.setRowFilter(null);

                } else {
                    rowSorter.setRowFilter(RowFilter.regexFilter(OwO));
                }
            }

            @Override
            public void removeUpdate(DocumentEvent e) {
                String OwO = txtSearch.getText();
                if (OwO.trim().length() == 0) {
                    rowSorter.setRowFilter(null);
                } else {
                    rowSorter.setRowFilter(RowFilter.regexFilter(OwO)); //"(?i)" +
                }
            }

            @Override
            public void changedUpdate(DocumentEvent e) {

            }
        });
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        jDialog2 = new javax.swing.JDialog();
        txtTendv = new javax.swing.JTextField();
        txtDongia = new javax.swing.JTextField();
        txtNgaysudung = new javax.swing.JTextField();
        txtSoluong = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        delbtn = new javax.swing.JButton();
        updatebtn = new javax.swing.JButton();
        savebtn = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        tool = new javax.swing.JPanel();
        Close = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        main1 = new javax.swing.JPanel();
        jpPhai = new javax.swing.JPanel();
        jpTren1 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jpDuoi1 = new javax.swing.JPanel();
        addDvbtn = new javax.swing.JButton();
        jpGiua1 = new javax.swing.JPanel();
        jPanel10 = new javax.swing.JPanel();
        jScrollPane4 = new javax.swing.JScrollPane();
        choosenServices = new javax.swing.JTable();
        jPanel11 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jPanel6 = new javax.swing.JPanel();
        saveService = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tablelichsusudung = new javax.swing.JTable();
        jpTrai = new javax.swing.JPanel();
        jpTren = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        txtSearch = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        filler1 = new javax.swing.Box.Filler(new java.awt.Dimension(5, 0), new java.awt.Dimension(5, 0), new java.awt.Dimension(5, 32767));
        jPanel3 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel9 = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        serviceList = new javax.swing.JTable();

        jDialog2.setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        jDialog2.setBackground(new java.awt.Color(255, 153, 153));
        jDialog2.setMinimumSize(new java.awt.Dimension(500, 400));
        jDialog2.getContentPane().setLayout(new java.awt.GridBagLayout());

        txtTendv.setEditable(false);
        txtTendv.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTendvActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.gridwidth = 3;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.weightx = 0.1;
        gridBagConstraints.weighty = 0.1;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 0, 30);
        jDialog2.getContentPane().add(txtTendv, gridBagConstraints);

        txtDongia.setEditable(false);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.gridwidth = 3;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.weightx = 0.1;
        gridBagConstraints.weighty = 0.1;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 0, 30);
        jDialog2.getContentPane().add(txtDongia, gridBagConstraints);

        txtNgaysudung.setEditable(false);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.gridwidth = 3;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.weightx = 0.1;
        gridBagConstraints.weighty = 0.1;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 0, 30);
        jDialog2.getContentPane().add(txtNgaysudung, gridBagConstraints);

        txtSoluong.setEditable(false);
        txtSoluong.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtSoluongActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.gridwidth = 3;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.weightx = 0.1;
        gridBagConstraints.weighty = 0.1;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 0, 30);
        jDialog2.getContentPane().add(txtSoluong, gridBagConstraints);

        jLabel3.setText("Tên dịch vụ");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.weightx = 0.1;
        gridBagConstraints.weighty = 0.1;
        jDialog2.getContentPane().add(jLabel3, gridBagConstraints);

        jLabel4.setText("Đơn giá");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.weightx = 0.1;
        gridBagConstraints.weighty = 0.1;
        jDialog2.getContentPane().add(jLabel4, gridBagConstraints);

        jLabel5.setText("Ngày sử Dụng");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.weightx = 0.1;
        gridBagConstraints.weighty = 0.1;
        jDialog2.getContentPane().add(jLabel5, gridBagConstraints);

        jLabel6.setText("Số Lượng");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.weightx = 0.1;
        gridBagConstraints.weighty = 0.1;
        jDialog2.getContentPane().add(jLabel6, gridBagConstraints);

        delbtn.setText("Xóa");
        delbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                delbtnActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 6;
        gridBagConstraints.weightx = 0.3;
        gridBagConstraints.weighty = 0.1;
        jDialog2.getContentPane().add(delbtn, gridBagConstraints);

        updatebtn.setText("Sửa");
        updatebtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updatebtnActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 6;
        gridBagConstraints.weightx = 0.3;
        gridBagConstraints.weighty = 0.1;
        jDialog2.getContentPane().add(updatebtn, gridBagConstraints);

        savebtn.setText("Lưu");
        savebtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                savebtnActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 6;
        gridBagConstraints.weightx = 0.3;
        gridBagConstraints.weighty = 0.1;
        jDialog2.getContentPane().add(savebtn, gridBagConstraints);

        jLabel8.setFont(new java.awt.Font("Times New Roman", 3, 18)); // NOI18N
        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel8.setText("Cập nhật dịch vụ khách hàng");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridwidth = 4;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.ipady = 9;
        gridBagConstraints.weightx = 0.1;
        gridBagConstraints.weighty = 0.1;
        jDialog2.getContentPane().add(jLabel8, gridBagConstraints);

        jButton2.setText("Hủy");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 6;
        jDialog2.getContentPane().add(jButton2, gridBagConstraints);

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setUndecorated(true);

        tool.setBackground(new java.awt.Color(255, 204, 102));
        tool.setPreferredSize(new java.awt.Dimension(992, 30));
        tool.setLayout(new java.awt.BorderLayout());

        Close.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/icons8_delete_24px.png"))); // NOI18N
        Close.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                CloseMouseClicked(evt);
            }
        });
        tool.add(Close, java.awt.BorderLayout.LINE_END);

        jPanel2.setOpaque(false);
        jPanel2.setLayout(new java.awt.BorderLayout());

        jLabel2.setFont(new java.awt.Font("Times New Roman", 3, 18)); // NOI18N
        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/View/food.png"))); // NOI18N
        jLabel2.setText("Dịch vụ khách hàng");
        jLabel2.setToolTipText("");
        jLabel2.setPreferredSize(new java.awt.Dimension(200, 13));
        jPanel2.add(jLabel2, java.awt.BorderLayout.LINE_START);

        tool.add(jPanel2, java.awt.BorderLayout.CENTER);

        getContentPane().add(tool, java.awt.BorderLayout.PAGE_START);

        main1.setBackground(new java.awt.Color(204, 204, 255));
        main1.setLayout(new java.awt.BorderLayout(10, 0));

        jpPhai.setBackground(main1.getBackground());
        jpPhai.setPreferredSize(new java.awt.Dimension(500, 610));
        jpPhai.setRequestFocusEnabled(false);
        jpPhai.setLayout(new java.awt.BorderLayout(0, 5));

        jpTren1.setPreferredSize(new java.awt.Dimension(500, 90));
        jpTren1.setLayout(new java.awt.GridLayout(1, 0));

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/rsz_resort-la-gi.jpg"))); // NOI18N
        jpTren1.add(jLabel7);

        jpPhai.add(jpTren1, java.awt.BorderLayout.PAGE_START);

        jpDuoi1.setLayout(new java.awt.GridLayout(1, 0));

        addDvbtn.setBackground(new java.awt.Color(255, 153, 153));
        addDvbtn.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        addDvbtn.setForeground(new java.awt.Color(255, 0, 51));
        addDvbtn.setText("Thêm dịch vụ ");
        addDvbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addDvbtnActionPerformed(evt);
            }
        });
        jpDuoi1.add(addDvbtn);

        jpPhai.add(jpDuoi1, java.awt.BorderLayout.PAGE_END);

        jpGiua1.setBackground(main1.getBackground());
        jpGiua1.setLayout(new java.awt.BorderLayout(0, 10));

        jPanel10.setPreferredSize(new java.awt.Dimension(500, 200));
        jPanel10.setLayout(new java.awt.GridLayout(1, 0));

        choosenServices.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Mã dịch vụ", "Tên dịch vụ", "Đơn vị", "Đơn giá", "Số lượng"
            }
        ));
        choosenServices.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                choosenServicesMouseClicked(evt);
            }
        });
        jScrollPane4.setViewportView(choosenServices);

        jPanel10.add(jScrollPane4);

        jpGiua1.add(jPanel10, java.awt.BorderLayout.PAGE_END);

        jPanel11.setBackground(main1.getBackground());
        jPanel11.setLayout(new java.awt.BorderLayout());

        jPanel4.setBackground(main1.getBackground());
        jPanel4.setOpaque(false);
        jPanel4.setPreferredSize(new java.awt.Dimension(50, 268));
        jPanel4.setLayout(new java.awt.BorderLayout());

        jPanel6.setLayout(new java.awt.GridLayout(1, 0));

        saveService.setBackground(new java.awt.Color(255, 153, 153));
        saveService.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        saveService.setForeground(new java.awt.Color(255, 0, 51));
        saveService.setText("<html>Cập<br>nhật<br>lịch<br>sử<br>Dịch<br>vụ</html>");
        saveService.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveServiceActionPerformed(evt);
            }
        });
        jPanel6.add(saveService);

        jPanel4.add(jPanel6, java.awt.BorderLayout.CENTER);

        jPanel11.add(jPanel4, java.awt.BorderLayout.LINE_END);

        tablelichsusudung.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Tên dịch vụ", "Đơn giá", "Ngày dùng", "Số lượng"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tablelichsusudung.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tablelichsusudungMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tablelichsusudung);

        jPanel11.add(jScrollPane1, java.awt.BorderLayout.CENTER);

        jpGiua1.add(jPanel11, java.awt.BorderLayout.CENTER);

        jpPhai.add(jpGiua1, java.awt.BorderLayout.CENTER);

        main1.add(jpPhai, java.awt.BorderLayout.LINE_END);

        jpTrai.setLayout(new java.awt.BorderLayout());

        jpTren.setPreferredSize(new java.awt.Dimension(480, 150));
        jpTren.setLayout(new java.awt.BorderLayout());

        jPanel1.setBackground(main1.getBackground());
        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED), "Nhập tên dịch vụ", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Times New Roman", 3, 10))); // NOI18N
        jPanel1.setMinimumSize(new java.awt.Dimension(100, 60));
        jPanel1.setName(""); // NOI18N
        jPanel1.setPreferredSize(new java.awt.Dimension(480, 60));
        jPanel1.setRequestFocusEnabled(false);
        jPanel1.setLayout(new java.awt.GridBagLayout());

        txtSearch.setToolTipText("");
        txtSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtSearchActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.ipady = 12;
        gridBagConstraints.weightx = 1.0;
        jPanel1.add(txtSearch, gridBagConstraints);

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/View/tools-and-utensils1.png"))); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.weightx = 0.15;
        jPanel1.add(jButton1, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 0;
        jPanel1.add(filler1, gridBagConstraints);

        jpTren.add(jPanel1, java.awt.BorderLayout.PAGE_END);

        jPanel3.setLayout(new java.awt.GridLayout(1, 0));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/rsz_5phoi-canh-khach-san-dep_30-1024x683.jpg"))); // NOI18N
        jPanel3.add(jLabel1);

        jpTren.add(jPanel3, java.awt.BorderLayout.CENTER);

        jpTrai.add(jpTren, java.awt.BorderLayout.PAGE_START);

        jPanel9.setLayout(new java.awt.GridLayout(1, 0));

        serviceList.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Mã dịch vụ", "Tên dịch vụ", "Đơn vị", "Đơn giá"
            }
        ));
        serviceList.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                serviceListMouseClicked(evt);
            }
        });
        jScrollPane3.setViewportView(serviceList);

        jPanel9.add(jScrollPane3);

        jpTrai.add(jPanel9, java.awt.BorderLayout.CENTER);

        main1.add(jpTrai, java.awt.BorderLayout.CENTER);

        getContentPane().add(main1, java.awt.BorderLayout.CENTER);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void serviceListMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_serviceListMouseClicked
        if (choosenServices.getRowCount() > 0) {
            int dem = 0;
            for (int i = 0; i < choosenServices.getRowCount(); i++) {
                if (choosenServices.getValueAt(i, 0) == serviceList.getValueAt(serviceList.getSelectedRow(), 0)) {
                    int soluong = (int) choosenServices.getValueAt(i, 4) + 1;
                    choosenServices.setValueAt(soluong, i, 4);
                    dem += 1;
                }
            }
            if (dem == 0) {
                ArrayList<Dichvu> ListZZZ = new ArrayList<>();
                // serviceList.setDefaultEditor(Object.class,null);
                Dichvu services
                        = new Dichvu((int) serviceList.getValueAt(serviceList.getSelectedRow(), 0),
                                serviceList.getValueAt(serviceList.getSelectedRow(), 1).toString(),
                                serviceList.getValueAt(serviceList.getSelectedRow(), 2).toString(),
                                (int) serviceList.getValueAt(serviceList.getSelectedRow(), 3));
                ListZZZ.add(services);
                Object[] row = new Object[6];
                row[0] = ListZZZ.get(0).getMadv();
                row[1] = ListZZZ.get(0).getTendv();
                row[2] = ListZZZ.get(0).getDvtinh();
                row[3] = ListZZZ.get(0).getDongia();
                row[4] = 1;
                ChoosenServicestablemodel.addRow(row);
                ListZZZ.remove(0);
                choosenServices.setModel(ChoosenServicestablemodel);
                choosenServices.updateUI();
            }
        } else {
            ArrayList<Dichvu> ListZZZ = new ArrayList<>();
            // serviceList.setDefaultEditor(Object.class,null);
            Dichvu services
                    = new Dichvu((int) serviceList.getValueAt(serviceList.getSelectedRow(), 0),
                            serviceList.getValueAt(serviceList.getSelectedRow(), 1).toString(),
                            serviceList.getValueAt(serviceList.getSelectedRow(), 2).toString(),
                            (int) serviceList.getValueAt(serviceList.getSelectedRow(), 3));
            ListZZZ.add(services);
            Object[] row = new Object[5];
            row[0] = ListZZZ.get(0).getMadv();
            row[1] = ListZZZ.get(0).getTendv();
            row[2] = ListZZZ.get(0).getDvtinh();
            row[3] = ListZZZ.get(0).getDongia();
            row[4] = 1;
            ChoosenServicestablemodel.addRow(row);
            ListZZZ.remove(0);
            choosenServices.setModel(ChoosenServicestablemodel);
            choosenServices.updateUI();

        }

    }//GEN-LAST:event_serviceListMouseClicked

    private void choosenServicesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_choosenServicesMouseClicked

        if ((int) choosenServices.getValueAt(choosenServices.getSelectedRow(), 4) == 1) {
            ChoosenServicestablemodel.removeRow(choosenServices.getSelectedRow());
            choosenServices.setModel(ChoosenServicestablemodel);
            choosenServices.updateUI();
        } else if ((int) choosenServices.getValueAt(choosenServices.getSelectedRow(), 4) > 1) {
            int soluong = (int) choosenServices.getValueAt(choosenServices.getSelectedRow(), 4) - 1;
            choosenServices.setValueAt(soluong, choosenServices.getSelectedRow(), 4);
        }

    }//GEN-LAST:event_choosenServicesMouseClicked

    //nut them vao lich su dịch vụ
    private void addDvbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addDvbtnActionPerformed
        Timestamp timestamp = new Timestamp(System.currentTimeMillis());
        for (int i = 0; i < choosenServices.getRowCount(); i++) {
            Dichvuphong dichvuphong = new Dichvuphong();
            dichvuphong.setMathuephong(mathuephong$);
            dichvuphong.setMadv((int) choosenServices.getValueAt(i, 0));
            dichvuphong.setDongia((int) choosenServices.getValueAt(i, 3));
            dichvuphong.setNgaydung(timestamp);
            dichvuphong.setMaphong(maphong$);
            dichvuphong.setSoluong((int) choosenServices.getValueAt(i, 4));
            serviceModel.insertRoomService(dichvuphong);
            tablelichsusudung.removeAll();
            adddichvuphong();
        }
        JOptionPane.showMessageDialog(null, "Đã lưu dịch vụ");
    }//GEN-LAST:event_addDvbtnActionPerformed

    private void saveServiceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveServiceActionPerformed
        tablelichsusudung.setEnabled(true);
        tablelichsusudung.requestFocus();
    }//GEN-LAST:event_saveServiceActionPerformed

    private void txtSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtSearchActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtSearchActionPerformed

    private void tablelichsusudungMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tablelichsusudungMouseClicked
        //int x = JOptionPane.showConfirmDialog(null, "Sửa ?", "Chắc ko? ", JOptionPane.OK_CANCEL_OPTION);
        //if (x == 0) {
        //   System.out.print("XXXXX");
        // },String tendv , String dongia , String ngaydung ,String soluong , int mathuephong , int maphong
        /*UpdateServicebtn aaaaaazs;
        aaaaaazs = new UpdateServicebtn(null, true,
                tablelichsusudung.getValueAt(tablelichsusudung.getSelectedRow(), 0).toString(),
                tablelichsusudung.getValueAt(tablelichsusudung.getSelectedRow(), 1).toString(),
                tablelichsusudung.getValueAt(tablelichsusudung.getSelectedRow(), 2).toString(),
                tablelichsusudung.getValueAt(tablelichsusudung.getSelectedRow(), 3).toString(),
                mathuephong$, maphong$);
        aaaaaazs.setVisible(true);
        aaaaaazs.resize(500, 400);*/
//        if (evt.getClickCount() == 2) {
        txtTendv.setText(tablelichsusudung.getValueAt(tablelichsusudung.getSelectedRow(), 0).toString());
        txtDongia.setText(tablelichsusudung.getValueAt(tablelichsusudung.getSelectedRow(), 1).toString());
        txtNgaysudung.setText(tablelichsusudung.getValueAt(tablelichsusudung.getSelectedRow(), 2).toString());
        txtSoluong.setText(tablelichsusudung.getValueAt(tablelichsusudung.getSelectedRow(), 3).toString());
        jDialog2.setVisible(true);
        jDialog2.setAlwaysOnTop(true);
        jDialog2.setFocusable(true);
        jDialog2.setAutoRequestFocus(true);
        setVisible(false);
//        }
        /* Point p = MouseInfo.getPointerInfo().getLocation();
        int x = p.x;
        int y = p.y;
        jDialog2.setLocation(x, y + 30);
        jDialog2.setVisible(true);*/
    }//GEN-LAST:event_tablelichsusudungMouseClicked

    private void txtTendvActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTendvActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTendvActionPerformed

    private void txtSoluongActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtSoluongActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtSoluongActionPerformed

    private void delbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_delbtnActionPerformed
        Dichvuphong dichvuphong = new Dichvuphong();
        dichvuphong.setMathuephong(mathuephong$);
        dichvuphong.setTendichvu(txtTendv.getText());
        dichvuphong.setNgaydung(Timestamp.valueOf(txtNgaysudung.getText()));
        dichvuphong.setMaphong(maphong$);
        serviceModel.deleteRoomService(dichvuphong);
        JOptionPane.showMessageDialog(null, "Đã xóa dịch vụ");
        jDialog2.setAlwaysOnTop(false);
        adddichvuphong();

        jDialog2.dispose();
        setVisible(true);

    }//GEN-LAST:event_delbtnActionPerformed

    private void updatebtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updatebtnActionPerformed
        txtSoluong.setEditable(true);
        txtSoluong.requestFocus();
        txtSoluong.selectAll();
    }//GEN-LAST:event_updatebtnActionPerformed
// nut lưu dịch vụ cần update
    private void savebtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_savebtnActionPerformed
        try {
            int x = JOptionPane.showConfirmDialog(null, "Chắc hok ?", "Are you sure about that ?", JOptionPane.YES_NO_OPTION);
            if (x == 0) {
                Dichvuphong dichvuphong = new Dichvuphong();
                dichvuphong.setSoluong(Integer.valueOf(txtSoluong.getText()));
                dichvuphong.setMathuephong(mathuephong$);
                dichvuphong.setTendichvu(txtTendv.getText());
                dichvuphong.setNgaydung(Timestamp.valueOf(txtNgaysudung.getText()));
                dichvuphong.setMaphong(maphong$);
                serviceModel.updateRoomService(dichvuphong);
                jDialog2.setAlwaysOnTop(false);
                jDialog2.setVisible(false);
                JOptionPane.showMessageDialog(null, "Đã sửa dịch vụ");
                adddichvuphong();
                setVisible(true);
                tablelichsusudung.setEnabled(false);
                tablelichsusudung.requestFocus();
            }

        } catch (Exception U) {
            System.err.println(U);
        }
    }//GEN-LAST:event_savebtnActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed

        jDialog2.setAlwaysOnTop(false);
        jDialog2.setVisible(false);
        setVisible(true);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void CloseMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CloseMouseClicked
        dispose();
    }//GEN-LAST:event_CloseMouseClicked

    private void adddichvuphong() {
        try {
            if (DichvuphongModel.getRowCount() > 0) {
                for (int i = DichvuphongModel.getRowCount() - 1; i > -1; i--) {
                    DichvuphongModel.removeRow(i);
                }
            }
            SimpleDateFormat formatter = new SimpleDateFormat("yyyy/MM/dd HH:mm:ss");
            ArrayList<Dichvuphong> dvphonglist = serviceModel.getDichvuphong(maphong$, mathuephong$);
            for (int i = 0; i < dvphonglist.size(); i++) {
                Object[] row = new Object[5];
                row[0] = dvphonglist.get(i).getTendichvu();
                row[1] = dvphonglist.get(i).getDongia();
                row[2] = dvphonglist.get(i).getNgaydung();
                row[3] = dvphonglist.get(i).getSoluong();
                DichvuphongModel.addRow(row);
                tablelichsusudung.setModel(DichvuphongModel);
                tablelichsusudung.updateUI();
            }
        } catch (SQLException ex) {
            Logger.getLogger(ServiceForm.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    private void Sorttable(JTable jTable) {
        TableRowSorter<TableModel> sorter = new TableRowSorter<>(jTable.getModel());
        jTable.setRowSorter(sorter);
        //  List<RowSorter.SortKey> sortKeys = new ArrayList<>();
        java.util.List<RowSorter.SortKey> sortkey = new ArrayList<>();
        int columnIndexToSort = 0;
        sortkey.add(new RowSorter.SortKey(columnIndexToSort, SortOrder.ASCENDING));
        sorter.setSortKeys(sortkey);
        sorter.sort();
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ServiceForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ServiceForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ServiceForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ServiceForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                ServiceForm dialog = new ServiceForm(new javax.swing.JFrame(), true, 101, 2);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });

                dialog.setVisible(true);
            }
        });
    }
    Object[] columnsname = {"Mã Dịch Vụ", "Tên Dịch Vụ", "Đơn vị Tính", "ĐƠn giá"};
    Object[] columnsnamedichvudachon = {"Mã Dịch Vụ", "Tên Dịch Vụ", "Đơn vị Tính", "ĐƠn giá", "Số lượng"};
    Object[] columnsname2 = {"Tên Dịch Vụ", "ĐƠn giá", "Ngày dùng", "Số lượng"};

    static Class getaClass2(int column) {
        switch (column) {
            case 0:
                return String.class;
            case 3:
                return Integer.class;
            case 1:
                return Integer.class;
            case 2:
                return String.class;
        }
        return null;
    }

    static Class getaClass(int column) {
        switch (column) {
            case 0:
                return Integer.class;
            case 3:
                return Integer.class;
            case 4:
                return Integer.class;
            case 1:
                return String.class;
            case 2:
                return String.class;
        }
        return null;
    }
    DefaultTableModel Servicestablemodel = new DefaultTableModel(columnsname, 0) {
        @Override
        public Class<?> getColumnClass(int columnIndex) {
            return super.getColumnClass(columnIndex);
        }
    };
    DefaultTableModel ChoosenServicestablemodel = new DefaultTableModel(columnsnamedichvudachon, 0) {
        @Override
        public Class<?> getColumnClass(int columnIndex) {
            return super.getColumnClass(columnIndex);
        }
    };
    DefaultTableModel DichvuphongModel = new DefaultTableModel(columnsname2, 0) {
        @Override
        public Class<?> getColumnClass(int columnIndex) {
            return super.getColumnClass(columnIndex);
        }
    };

    // Đưa ra bảng danh sách dịch vụ
    void AddServices() {
        try {
            ArrayList<Dichvu> ListServices = new ServiceModel().getDichvu();
            Object[] row = new Object[4];
            for (int i = 0; i < ListServices.size(); i++) {
                row[0] = ListServices.get(i).getMadv();
                row[1] = ListServices.get(i).getTendv();
                row[2] = ListServices.get(i).getDvtinh();
                row[3] = ListServices.get(i).getDongia();
                Servicestablemodel.addRow(row);
            }
            serviceList.setModel(Servicestablemodel);
            serviceList.updateUI();

        } catch (Exception Ư) {
            System.out.println(Ư);
        }

    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Close;
    private javax.swing.JButton addDvbtn;
    private javax.swing.JTable choosenServices;
    private javax.swing.JButton delbtn;
    private javax.swing.Box.Filler filler1;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JDialog jDialog2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JPanel jpDuoi1;
    private javax.swing.JPanel jpGiua1;
    private javax.swing.JPanel jpPhai;
    private javax.swing.JPanel jpTrai;
    private javax.swing.JPanel jpTren;
    private javax.swing.JPanel jpTren1;
    private javax.swing.JPanel main1;
    private javax.swing.JButton saveService;
    private javax.swing.JButton savebtn;
    private javax.swing.JTable serviceList;
    private javax.swing.JTable tablelichsusudung;
    private javax.swing.JPanel tool;
    private javax.swing.JTextField txtDongia;
    private javax.swing.JTextField txtNgaysudung;
    private javax.swing.JTextField txtSearch;
    private javax.swing.JTextField txtSoluong;
    private javax.swing.JTextField txtTendv;
    private javax.swing.JButton updatebtn;
    // End of variables declaration//GEN-END:variables
}
